### ISSUE TITLE
Some sites do not work

### ISSUE THREAD

**Issue by gastongaston** [kimiko88/Tvos-PornSitesViewer#1]
Hi,

thanks for the great work! Once sorting and log ins are added, it will be even better. I have noticed that Pornhub, Xvideos and xTube do not work, apart from that it works really well. Thanks again!

**Comment by kimiko88** [comment]
Sorry for being late but now I fix the Xvideos bug, later I try to fix Pornhub and xTube.
I don't know if login can be done for all that sites but in future I'll try.
In the next day i'll try to add sorting.

Thanks to you!

**Comment by iKorich** [comment]
fix Pornhub - 
```
var imageLink = Utils.GetStringsByRegularExpression(stringa, regularexp:
                "<img\\s+(?:[^>]*?\\s+)?data-end")//"<img\\s+(?:[^>]*?\\s+)?src=\"http://([^\"]*)?([^<]*)"
```
to
```
var imageLink = Utils.GetStringsByRegularExpression(stringa, regularexp:
                "<img.*?src=\"([^\"]*)\".*?data-end=\"*\"[^>]*>")
```

**Comment by iKorich** [comment]
fix XTube

HomeSelectionController.swift
line 139: ThumbzillaCharge(url) -> XTubeCharge(url)

**Comment by kimiko88** [comment]
Really thanks @iKorich ! 
I hope to have more time to add some feature at this project.
